name: XTF Maven Release

on:
  push:
    branches:
      - '**'
jobs:

  test:
    name: Deploy to JBoss Snapshots Maven repo
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jdk
          architecture: x64
      - name: Check well-formatted code
        run: mvn -B formatter:validate impsort:check
      - name: Maven Package
        run: mvn install -B -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: Maven Verify
        run: mvn -B clean verify
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v12
        with:
          servers: '[{ "id": "jboss-releases-repository", "username": "${env.JBOSS_REPO_USER}", "password": "${env.JBOSS_REPO_PASSWORD}" },{ "id": "jboss-snapshots-repository", "username": "${env.JBOSS_REPO_USER}", "password": "${env.JBOSS_REPO_PASSWORD}" }]'
      - name: Maven Deploy
        run: mvn -X deploy -DskipTests
        env:
          JBOSS_REPO_PASSWORD: ${{ secrets.JBOSS_REPO_PASSWORD }}
          JBOSS_REPO_USER: ${{ secrets.JBOSS_REPO_USER }}

